# Generated by Django 4.1.4 on 2022-12-18 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_art_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(default='Anonymous', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ArtOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_orders', to='home.art')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_orders', to='home.customer')),
            ],
        ),
    ]
