# Generated by Django 4.1.4 on 2022-12-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer_artorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artorder',
            name='art',
        ),
        migrations.AddField(
            model_name='art',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artorder',
            name='arts',
            field=models.ManyToManyField(related_name='art_orders', to='home.art'),
        ),
    ]
