# Generated by Django 4.1.4 on 2022-12-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_artorder_art_art_available_artorder_arts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artorder',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
