# Generated by Django 4.1.4 on 2023-01-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('user_username', models.CharField(max_length=200)),
                ('staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(unique=True)),
                ('sender_id', models.BigIntegerField()),
                ('sender_is_bot', models.BooleanField()),
                ('sender_username', models.CharField(max_length=200)),
                ('chat_id', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('reply_to_message_id', models.BigIntegerField(null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True)),
                ('message_id', models.BigIntegerField(unique=True)),
                ('sender_id', models.BigIntegerField()),
                ('sender_is_bot', models.BooleanField()),
                ('sender_username', models.CharField(max_length=200)),
                ('chat_id', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('reply_to_message_id', models.BigIntegerField(null=True)),
                ('text', models.TextField(null=True)),
                ('bot_command', models.BooleanField()),
            ],
        ),
    ]
